### ISSUE TITLE
Результат "Заменить все"?

### ISSUE THREAD

**Issue by ainoneko** [egovoryn/math#1]
В https://github.com/egovoryn/math/blob/517474d6b3d0526957ef1ef02335acc8d4b71ec2/v1_math.h#L20 
и следующей строке (не знаю, как тут отметить несколько строк) в комментариях встречается `v1` вместо `eg`:

#define v1_INT_MIN -2147483648  // Max n**v1**ative int**v1**er
#define v1_INT_MAX 2147483647   // Max positive int**v1**er

**Comment by gdegor** [comment]
Спасибо)
