### ISSUE TITLE
Число "пи"

### ISSUE THREAD

**Issue by ainoneko** [egovoryn/math#2]
https://github.com/egovoryn/math/blob/517474d6b3d0526957ef1ef02335acc8d4b71ec2/v1_math.h#L11
Число "пи" определено с ошибкой (после `3.14159265358979323846` должно быть `2643383...`, а не `50288`.
Но это не влияет на работу программы, так как точность double кончается ещё раньше, после 
**`3.141592653589793`**(дальше получается `115997963468544` вместо `23846`...).
¯\\\_(ツ)\_\/¯

**Comment by gdegor** [comment]
Спасибо)
